version: '3.8'

services:
  app:
    image: registry.cn-hangzhou.aliyuncs.com/insigma/bay-rewards:login-service
    volumes:
      - .:/data
    ports:
      - "4200:4200"
    environment:
      MIX_ENV: dev
